### ISSUE TITLE
layer.name causes intermediate sources with duplicate locations

### ISSUE THREAD

**Issue by schriftgestalt** [googlefonts/glyphsLib#851] opened 2023-01-20 12:05 UTC
The `layer.name` should not be used for anything. Only when opening v2 files to convert to `layer.attributes`.

In Glyphs 3, `layer.name` is generated from the attributes but is only used for UI purposes. 

I just found a problem where two glyphs with a brace layer for the same position would generate duplicate `SourceDescriptor`s because of different names.

```
WARNING:glyphsLib.builder.sources:DesignSpace sources contain duplicate locations; varLib expects each master to define a unique location. Make sure that you used consistent 'brace layer' names in all the glyph layers that share the same location.
  ['{110, 0}', '25. May 22, 21:39'] => {'Weight': 110, 'Ascender': 0}
```

**Comment by ktkm** [comment] 2023-03-21 09:49
I have this issue now when building from v3 files. This means I can only use one set of coordinates for one glyph at a time. Is there a workaround?

**Comment by kontur** [comment] 2023-05-02 12:33
Encountered the same issue. For now I could only find that the Glyphs UI hides the "date name" of the layer when activating it as a e.g. "Intermediate" layer type, so finding what glyph actually causes this new layer in the UFO is a PITA. No idea as of yet where in glyphsLib the layer name is used to result in those in the extracted UFOs and then subsequently results in failed designspaces.

**Comment by schriftgestalt** [comment] 2023-05-02 13:16
The layer.name should not use at all anymore.

**Comment by kontur** [comment] 2023-05-02 17:46
The error message is almost word by word the above

> WARNING:glyphsLib.builder.sources:DesignSpace sources contain duplicate locations; varLib expects each master to define a unique location. Make sure that you used consistent 'brace layer' names in all the glyph layers that share the same location.
  ['{110, 0}', '25. May 22, 21:39'] => {'Weight': 110, 'Ascender': 0}

It seems somewhere the glyph layer name makes it into the master/source name. I'm condense my file into something testable.

**Comment by kontur** [comment] 2023-05-03 07:21
Printing the `duplicates` [here](https://github.com/googlefonts/glyphsLib/blob/6372da0c1f77cad3152364c2473b7a380ac6c301/Lib/glyphsLib/builder/sources.py#L50) I get:

```
{(('Weight', 22.0), ('Width', 100.0)): [SourceDescriptor(
    filename='Foobar-CondensedBold.ufo',
    path=None,
    name='Foobar Condensed Bold {22, 100}',
    layerName='{22, 100}',
    location=OrderedDict([('Weight', 22.0), ('Width', 100.0)]),
    copyLib=False,
    copyGroups=False,
    copyFeatures=False,
    muteKerning=False,
    muteInfo=False,
    mutedGlyphNames=[],
    familyName=None,
    styleName=None,
    localisedFamilyName={},
), SourceDescriptor(
    filename='Foobar-CondensedBold.ufo',
    path=None,
    name='Foobar Condensed Bold {22,\u2009100}',
    layerName='{22,\u2009100}',
    location=OrderedDict([('Weight', 22.0), ('Width', 100.0)]),
    copyLib=False,
    copyGroups=False,
    copyFeatures=False,
    muteKerning=False,
    muteInfo=False,
    mutedGlyphNames=[],
    familyName=None,
    styleName=None,
    localisedFamilyName={},
)], ...
```

So the `location` is the same but the different `layerName='{22, 100}',` vs `layerName='{22,\u2009100}',` triggers the warning:

```
DesignSpace sources contain duplicate locations; varLib expects each master to define a unique location. Make sure that you used consistent 'brace layer' names in all the glyph layers that share the same location.
  ['{22, 100}', '{22,\u2009100}'] => {'Weight': 22.0, 'Width': 100.0}
  ...
```

The above comment with the layer name being a date also points to glyphsLib using layernames instead of location coordinates somewhere. In Glyphs you can create a layer, keep the automatic (date) layer name, right click and set it as "Intermediate", set location values and it will display in the UI as brace layer, but the underlying layer name remains the date, as evident by right clicking and unchecking the "Intermediate" and it will resurface the actual layer name property.

I am wondering if this again has to do with some kind of conversion from glyphs file format 2 to 3 and some layer names are left in an old format. However, when I, in Glyphs, output the layer names I get exclusively the same, e.g. for that location:

```
for g in Glyphs.font.glyphs:
	for l in g.layers:
		if l.attributes["coordinates"]:
			print(l.name, [c for c in l.name], l.attributes["coordinates"])

{22, 100} ['{', '2', '2', ',', '\u2009', '1', '0', '0', '}'] {
    a01 = 22;
    a02 = 100;
}
{22, 100} ['{', '2', '2', ',', '\u2009', '1', '0', '0', '}'] {
    a01 = 22;
    a02 = 100;
}
{22, 100} ['{', '2', '2', ',', '\u2009', '1', '0', '0', '}'] {
    a01 = 22;
    a02 = 100;
}
...
```

Looking at the extracted UFOs there seems to be one glyph that has the "additional" 22, 100 location. Looking at it in Glyphs I check the layer names as displayed, and also when deactivating "Intermediate" the layer names seem "in line" with what is expected of those layer names.

<img width="472" alt="Screenshot 2023-05-03 at 10 17 16" src="https://user-images.githubusercontent.com/1893577/235853702-579bbb91-4686-4c72-b96e-d3d7d0ecbd80.png">
<img width="828" alt="Screenshot 2023-05-03 at 10 17 26" src="https://user-images.githubusercontent.com/1893577/235853714-d12e6703-690e-4068-9962-377bd171340f.png">
<img width="953" alt="Screenshot 2023-05-03 at 10 17 38" src="https://user-images.githubusercontent.com/1893577/235853717-52f9f5df-1828-40df-bf8e-17dd481d60f9.png">

Oddly, deleting everything but `O` and one of the glyphs listed in the "other" 22, 100 UFO I do not get the same error. I would expect those to have the same "double" location then. Alas, I don't have a minimal testing file just yet.

**Comment by kontur** [comment] 2023-05-03 07:56
Parsing the masters, [this creates](https://github.com/googlefonts/glyphsLib/blob/6372da0c1f77cad3152364c2473b7a380ac6c301/Lib/glyphsLib/builder/builders.py#L321) new UFO layers for brace layers, and `to_ufo_layer` just [sets the layer name](https://github.com/googlefonts/glyphsLib/blob/6372da0c1f77cad3152364c2473b7a380ac6c301/Lib/glyphsLib/builder/layers.py#L35) from the actual GlyphsApp layer name — and in the case of my file it just happens that those are not consequently named. E.g. I had `{20,\u20200}` and ` {20,\u2009200}` (which may or may not have to do with upgrading a v2 file to v3 or maybe is a change in GlyphsApp?) — but it also explains why I had earlier gotten the "date" layer name just as the original post above — as stated GlyphsApp ignores the layerName and shows something else in the UI (the coordinates attribute). Yet the actual layerName persist in the background, and then mistakenly gets parsed by glyphsLib as the assumed "coordinate layer name" — which it isn't.

**Comment by kontur** [comment] 2023-05-03 08:19
Tentatively: If I normalize `layer.name` from `layer.attributes["coordinates"]` (if available) to the expected format [here](https://github.com/googlefonts/glyphsLib/blob/6372da0c1f77cad3152364c2473b7a380ac6c301/Lib/glyphsLib/builder/builders.py#L280) the designspace and layers are extracted as they should. I can submit a PR fixing this specifically for "Intermediate" and reconstructing a layer name akin to `{axisvalue, axisvalue, ...}`, but the same issue probably applies to other special layer types which use the legacy approach of using the layer name instead of some v3 attribute.

**Comment by khaledhosny** [comment] 2023-05-03 09:57
Doesn't Glyphs has s different API function thst returns the UI layer name (constructing it basically)? May be we should add that and use it anywhere layer.name is used.

**Comment by anthrotype** [comment] 2023-05-03 10:14
> different API function

I think it's the same `name` property of GSLayer, not a different method. The result changes based on layer type and attributes.
If I print `Glyphs.font.selectedLayers[0].name` from the Macro window when inside one of these intermediate layers in Glyphs 3.app, it prints e.g. `{201}` when the layer is marked as "Intermediate" in the contextual menu; if I disable that, it gets back to the current date name. Since the user cannot edit the layer name when it is marked as one of the special layers, we must return whatever Glyphs 3.app returns; for v2 we should continue to use the actually stored layer name.
We do need _a_ name because UFO layers need to be named and they need to have a unique name.

**Comment by anthrotype** [comment] 2023-05-03 10:24
the problem is the underlying layer name (before the layer is turned into an intermediate layer with generated name property) is still saved to the .glyphs v3 file for some reasons, only that it cannot be edited from the UI. This is a bit weird...
I am not exactly sure how we can best match Glyphs 3.app behaviour here. On the one hand we want to obtain the UI layer name and use that for storing the UFO layer name; on the other hand, we might still be interested in keeping the old layer name (even though technically it does not carry any useful information.. if so why is it even retained at all?), so that saving back the .glyphs3 file does not produce unwanted diffs. But the two things are accessible via the same inteface (layer.name property).

**Comment by kontur** [comment] 2023-05-03 12:37
> We do need a name because UFO layers need to be named and they need to have a unique name.

And crucially for brace layers, the (UFO) layer names for identical axis locations need to be identical. Having these types of file top-level conditionals for different file versions trickle down to some attribute getters or writers is super unreadable; not happy with that PR approach, but needed something to at least be able to parse that file. :/

**Comment by kontur** [comment] 2023-05-04 05:38
I can't find any mention of `nameUI` in this repo, the glyphs API nor in a v3 glyphs source, only a [mention here](https://github.com/googlefonts/glyphsLib/pull/750#discussion_r751423908).

**Comment by khaledhosny** [comment] 2023-05-20 17:48
> > > different API function
> > 
> > 
> > I think it's the same `name` property of GSLayer, not a different method. The result changes based on layer type and attributes. If I print `Glyphs.font.selectedLayers[0].name` from the Macro window when inside one of these intermediate layers in Glyphs 3.app, it prints e.g. `{201}` when the layer is marked as "Intermediate" in the contextual menu; if I disable that, it gets back to the current date name. Since the user cannot edit the layer name when it is marked as one of the special layers, we must return whatever Glyphs 3.app returns; for v2 we should continue to use the actually stored layer name. We do need _a_ name because UFO layers need to be named and they need to have a unique name.
> 
> Looks like there is `layer.nameUI()` that returns the actual name (though the naming is confusing, shouldn’t `.name` return the actual name and `nameUI()` do the other way around? More confusingly, if you set `.name`, `.nameUI()` returns the new name while `.name` still gives the UI name).

@schriftgestalt can you confirm that this is the expected behavior of the API?

**Comment by khaledhosny** [comment] 2023-05-20 17:49
> I can't find any mention of `nameUI` in this repo, the glyphs API nor in a v3 glyphs source, only a [mention here](https://github.com/googlefonts/glyphsLib/pull/750#discussion_r751423908).

That comment is where I got the idea about `nameUI`, but what I found is a function not a property and it does not behave as suggested there.

**Comment by schriftgestalt** [comment] 2023-05-20 17:56
> @schriftgestalt can you confirm that this is the expected behavior of the API?

That is what is implemented. It seems to make more sense that `layer.name` would just return the manually set name and and layer.nameUI would return the computed value. There must be a reason why I did it like this.

nameUI is a simpler method, so you can’t set it.

**Comment by khaledhosny** [comment] 2023-05-20 17:56
Running this in Glyphs’ Macro Panel:
```python
layer = Glyphs.font.selection[0].layers[1]
print(layer.attributes)
print(layer.name)
print(layer.nameUI)
print(layer.nameUI())
```

Gives:
```
{
    coordinates =     {
        a01 = 0;
        a02 = 20;
    };
}
{0, 20}
<native-selector nameUI of <GSLayer 0x7fb6c59474a0> {0, 20} (hah-ar)>
{0, 10} 17 May 23 at 17:17
```

**Comment by schriftgestalt** [comment] 2023-05-20 19:33
There is another method that return the manually set name: 
```
layer.ownName()
```
This is not supposed to be used, just mentioned here for debugging purposes.

**Closed** 2023-07-11 16:25 UTC
