### ISSUE TITLE
Add FeatureParamsStylisticSet in FeatureRecord

### ISSUE THREAD

**Issue by kosbarts** [googlefonts/glyphsLib#662] opened 2021-02-05 10:02 UTC
Currently when exporting from a Glyphs file the custom naming of Features is dropped.
Is it possible to update and include it?

**Comment by anthrotype** [comment] 2021-02-05 10:14
this is implemented in this PR https://github.com/googlefonts/glyphsLib/pull/615

I actually forgot what the outstanding issues where that prevented the merge and have no time to dig deeper at the moment.

Maybe @jenskutilek or @madig remember?

**Comment by jenskutilek** [comment] 2021-02-10 17:08
I need to have a look again.

**Comment by khaledhosny** [comment] 2021-11-28 15:54
Duplicate of #602

**Closed by khaledhosny** 2021-11-28 15:54 UTC
