### ISSUE TITLE
Duplicate unicodes for color layers

### ISSUE THREAD

**Issue by yanone** [googlefonts/glyphsLib#943] opened 2023-09-06 13:41 UTC
Generating a color font with `fontmake` [currently leads to all layers receiving the base glyph’s unicode value](https://github.com/googlefonts/glyphsLib/blob/main/Lib/glyphsLib/builder/glyph.py#L60) which prevents the font from generating.

Current code:

`    ufo_glyph.unicodes = [int(uval, 16) for uval in glyph.unicodes]`

This works:

`    ufo_glyph.unicodes = [int(uval, 16) for uval in glyph.unicodes] if not ".color" in glyph.name else []`

My workaround is probably too simplistic as there may be other reasons that a layer is a secondary one and mustn’t get a unicode. What are other criteria?

As usual, I’m happy to prepare a PR.

**Comment by khaledhosny** [comment] 2023-09-06 14:06
Duplicate of #937

**Closed** 2023-09-06 14:07 UTC
